# Generated by Django 5.0.2 on 2024-03-10 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_profile_otp_alter_user_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='otp',
        ),
    ]
