# Generated by Django 5.0.2 on 2024-04-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_profile_address_user_profile_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
