# Generated by Django 5.0.2 on 2024-03-04 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryManagement',
        ),
    ]
