# Generated by Django 5.0.2 on 2024-03-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpanel', '0002_delete_gallerymanagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='Gallery_Images/')),
            ],
        ),
    ]
