# Generated by Django 5.0.2 on 2024-03-11 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddGallery',
            new_name='Gallery',
        ),
    ]
