# Generated by Django 5.0.2 on 2024-03-11 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_rename_addgallery_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.category'),
        ),
    ]
