# Generated by Django 5.0.2 on 2024-03-12 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0015_category_created_at_category_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
    ]
