# Generated by Django 5.0.2 on 2024-03-10 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wewindecoration', '0004_rename_userprofile_user_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Profile',
        ),
    ]
