# Generated by Django 5.0.2 on 2024-04-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wewindecoration', '0007_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
