# Generated by Django 5.0.2 on 2024-04-02 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0018_decoration'),
        ('wewindecoration', '0008_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='decoration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.decoration'),
        ),
    ]
