# Generated by Django 5.0.2 on 2024-04-02 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0018_decoration'),
        ('wewindecoration', '0009_order_decoration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='decoration',
        ),
        migrations.AddField(
            model_name='order',
            name='decorations',
            field=models.ManyToManyField(to='adminpanel.decoration'),
        ),
    ]
