# Generated by Django 5.0.2 on 2024-04-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0018_decoration'),
        ('wewindecoration', '0011_remove_order_decorations_order_decorations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='decorations',
        ),
        migrations.AddField(
            model_name='order',
            name='decorations',
            field=models.ManyToManyField(to='adminpanel.decoration'),
        ),
    ]
