# Generated by Django 5.0.2 on 2024-04-02 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wewindecoration', '0013_remove_order_decorations_order_decoration_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='decoration_images',
        ),
        migrations.CreateModel(
            name='OrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='order_images')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='wewindecoration.order')),
            ],
        ),
    ]
