# Generated by Django 5.0.2 on 2024-04-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wewindecoration', '0014_remove_order_decoration_images_orderimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderimage',
            name='image',
            field=models.ImageField(upload_to='Order_Images/'),
        ),
    ]
